### PR TITLE
Adding Singleton design pattern under creational

### PR DESCRIPTION
**Pull request by rameshgkaranth**

### CODE REVIEW

**Comment by nakshathri** [comment]
This is Lazily initialize the singleton class only when its required. Other way to implement is to create an instance the moment the class gets loaded by the class loader. @rameshgkaranth Can we add that as well ?

**Comment by rameshgkaranth** [comment]
@nakshathri - If a class is referred to in the code or explicitly initialised using Class.forName(), the static block of the code has to run. If I move the creation of Singleton class to this block, requirement would be met, isn't it?

However, downside is, in a multi threaded environment, if multiple threads tried to load the class I am not sure if we will still have one instance only.

Please let me know

**Comment by nakshathri** [comment]
@rameshgkaranth  : 

for example : 

private static final Singleton = new Singleton() 

OR 

private static final Singleton;

static{
singleton = new Singleton();
}

This will make sure that the instance is created when the class is loaded for the first time. Within a classloader, across multiple threads, classloader will ensure that class will be loaded only once. But if you want a single instance across multiple classloader, then it needs a different implementation. 

Let me know your comments.

**Comment by rameshgkaranth** [comment]
@nakshathri Added the static way as well.

**Pull request merged**
